import { TransformNode, Scene, Mesh, UniversalCamera } from "babylonjs";
export declare class CharacterController extends TransformNode {
    camera: UniversalCamera;
    scene: Scene;
    private input;
    mesh: Mesh;
    private camTransformDummy;
    private _yTilt;
    private static readonly PLAYER_SPEED;
    private static readonly JUMP_FORCE;
    private static readonly GRAVITY;
    private static readonly ORIGINAL_TILT;
    private deltaTime;
    private _h;
    private _v;
    private moveDirection;
    private _inputAmt;
    private _gravity;
    private _lastGroundPos;
    private _grounded;
    private readonly yOffest;
    private lookTime;
    private lookTimer;
    constructor(pawn: any, scene: Scene, createCamera: boolean, input?: any);
    SetupBeforeRenderUpdateLoop(): void;
    private UpdatePhysics;
    private UpdateCamera;
    private SetupCharacterCameraRoot;
    private CreateCharacterCamera;
    AssignCameraToCharacter(camera: UniversalCamera): void;
    private UpdateFromControls;
    private UpdateGroundDetection;
    private _floorRaycast;
    private _isGrounded;
    private LookRaycast;
}
